name: Changelog - Linear Tickets
description: 'Runs a script to generate changelog and post to notion db'

inputs:
  github-token:
    description: "A Github oauth token with sufficent permissions to read PRs, commits, and comments"
    required: true
  notion-token:
    description: "A Notion oauth token with write permissions" 
    required: true
  notion-db:
    description: "A notion database id to insert the released tickets into"
    required: true
  pull-request-number:
    description: "The pull request number for the release"
    required: true

runs:
  using: composite
  steps:
    - run: cp ${{ github.action_path }}/package-lock.json changelog-package-lock.json
      shell: bash
    - uses: actions/cache@v4
      id: cache-node-modules
      with:
        path: ${{ github.action_path }}/node_modules
        key: gh-common-changelog-npm-${{ hashFiles('changelog-package-lock.json') }}
    - run: npm install
      working-directory: ${{ github.action_path }}
      shell: bash
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
    - run: node linear-changelog.js
      working-directory: ${{ github.action_path }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NOTION_TOKEN: ${{ inputs.notion-token }}
        NOTION_DB: ${{ inputs.notion-db }}
        PULL_REQUEST_NUMBER: ${{ inputs.pull-request-number }}
