name: 'Install jq'
description: 'Installs jq'
runs:
  using: 'composite'
  steps:
    - name: 'Install jq'
      shell: bash
      run: |
        sudo apt-get update;
        sudo apt-get install jq;
