name: 'Notify Notion'
description: 'Adds a row to the Notion database'
inputs:
  database-id:
    description: "The id of the release status page database"
    required: true
  notion-secret:
    description: "Notion secret key"
    required: true
  repo:
    description: "Repository name"
    required: true
  sha:
    description: "The commit sha"
    required: true
  status:
    description: "Status to report"
    required: true
  body:
    description: "Body text of the database entry"
    required: false
    default: ""
  gh_automation_token:
    description: 'The gh actions token'
    required: true
  status:
    description: 'The status message to post'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Add masks'
      shell: bash
      run: |
        echo "::add-mask::${{ inputs.database-id }}"
        echo "::add-mask::${{ inputs.notion-secret }}"
        echo "::add-mask::${{ inputs.gh_automation_token }}"
    - name: checkout the private repository
      id: checkout_notion_action
      uses: actions/checkout@v3
      with:
        repository: onboardiq/gh-action-post-release-status-to-notion
        token: ${{ inputs.gh_automation_token }}
        path: ./action

    - name: run the action
      uses: ./action
      with:
        database-id: ${{ inputs.database-id }}
        notion-secret: ${{ inputs.notion-secret }}
        repo: ${{ inputs.repo }}
        sha: ${{ inputs.sha }}
        status: ${{ inputs.status }}
        body: ${{ inputs.body }}
