name: 'Notify Slack'
description: 'Sends the configured channel a message'
inputs:
  slack_webhook_url:
    description: 'The URL of the Slack Webhook to post the message to'
    required: true
  gh_automation_token:
    description: 'The gh actions token'
    required: true
  environment:
    description: 'The environment to which the code has been deployed'
    required: true
  message:
    description: 'The message to post'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Add masks'
      shell: bash
      run: |
        echo "::add-mask::${{ inputs.gh_automation_token }}"
        echo "::add-mask::${{ inputs.slack_webhook_url }}"

    - name: checkout the action
      id: checkout_slack_action
      uses: actions/checkout@v3
      with:
        repository: onboardiq/gh-action-post-message-to-slack
        token: ${{ inputs.gh_automation_token }}
        path: ./action
        fetch-depth: 1

    - name: run the action
      uses: ./action
      with:
        message: ${{ inputs.message }}
        slack_webhook_url: ${{ inputs.slack_webhook_url }}
