name: 'Helm Push'
description: 'Push Helm Chart to a given region'
inputs:
  image-name:
    description: 'The name of the image to use in the Helm chart'
    required: true
  helm-version:
    description: 'The version of Helm to use'
    required: true
  chart-version:
    description: 'The version of the helm chart'
    required: true
  repo-username:
    description: 'A username with sufficient permissions to push to the helm repo'
    required: true
  repo-password:
    description: 'A password matching the given repo username'
    required: true
  cloud:
    description: 'One of "aws" or "azure"'
    required: true
  region:
    description: 'An AWS or Azure region name'
    required: true
  token:
    description: 'A github token'
    default: ''
    required: true
  cluster-suffix:
    description: 'A string to differentiate between helm repos in the same region'
    default: ''
    
runs:
  using: 'composite'
  steps:
    - name: 'Add masks'
      shell: bash
      run: |
        echo "::add-mask::${{ inputs.repo-username }}"
        echo "::add-mask::${{ inputs.repo-password }}"
        echo "::add-mask::${{ inputs.token }}"

    - name: 'Checkout Github Action'
      uses: actions/checkout@v3
      with:
        repository: onboardiq/gh-common-workflows
        path: ./common-workflows
        fetch-depth: 0

    - id: version
      uses: ./common-workflows/.github/workflows/actions/version
      with:
        base-chart-version: ${{ inputs.chart-version }}

    - name: 'Install and Setup Helm'
      uses: Azure/setup-helm@v3.3
      with:
        version: ${{ inputs.helm-version }}
        token: ${{ inputs.token }}
        
    - name: 'Push Helm chart'
      env:
        CLOUD: ${{ inputs.cloud }}
        REGION: ${{ inputs.region }}
        CLUSTER_SUFFIX: ${{ inputs.cluster-suffix }}
        CHART_VERSION: ${{ steps.version.outputs.chart-version }}
        APP_VERSION: ${{ steps.version.outputs.image-tag }}
        IMAGE_TAG: ${{ steps.version.outputs.image-tag }}
        HELM_REPO_USERNAME: ${{ inputs.repo-username }}
        HELM_REPO_PASSWORD: ${{ inputs.repo-password }}
      shell: bash
      run: make -C helm artifact
