name: 'Version'
description: 'Determine the image tag and chart version given a specific git reference'
inputs:
  base-chart-version:
    description: "The base version of the form X.Y.Z for the helm chart"
    required: true
  ref:
    description: "The branch or tag name or SHA to check out"
    required: true
    type: string
  commit-sha:
    description: "The SHA corresponding to the above ref"
    required: true
    type: string
outputs:
  image-tag:
    description: "A string suitable for use as a Docker image"
    value: ${{ steps.image-tag.outputs.image-tag }}
  chart-version:
    description: "A string suitable for use as a Helm Chart version string"
    value: ${{ steps.chart-version.outputs.chart-version }}
runs:
  using: 'composite'
  steps:
    - id: image-tag
      shell: bash
      env:
        REF: ${{ inputs.ref }}
        SHA: ${{ inputs.commit-sha}}
      run: |
        echo "image-tag=${REF##*/}-${SHA::7}" >> $GITHUB_OUTPUT

    - id: chart-version
      shell: bash
      env:
        REF: ${{ inputs.ref }}
        SHA: ${{ inputs.commit-sha}}
      run: |
        if [[ ${REF} == *stable ]]; then
          echo "chart-version=${{ inputs.base-chart-version }}-${SHA::7}" >> $GITHUB_OUTPUT
        else
          FILTERED_REF=$( echo "${REF##*/}" | tr '_' '-' )
          echo "chart-version=${{ inputs.base-chart-version }}-${SHA::7}-${FILTERED_REF}" >> $GITHUB_OUTPUT
        fi
