name: 'CI'

on:
  workflow_call:
    inputs:
      project-name:
        description: "The name of the project"
        required: true
        type: string
      build-assets:
        description: "Whether to build Rails assets, defaults to false"
        default: false
        type: boolean
      helm-chart-version:
        description: "The version to give the Helm chart"
        required: true
        type: string
      helm-version:
        description: "The version of Helm to use"
        default: '3.4.1'
        type: string
      slack-channel:
        description: "The slack channel to post to on success"
        required: false
        type: string
      clusters:
        description: "A JSON string representing a list of clusters to push docker containers to"
        required: true
        type: string
    secrets:
      aws-access-key-id:
        description: "An AWS Access Key ID with sufficient access to push to ECR repos"
        required: true
      aws-secret-access-key:
        description: "An AWS Secret Access Key matching the given AWS Access Key ID"
        required: true
      azure-registry-username:
        description: "A username with sufficient access to push to ACR"
        required: true
      azure-registry-password:
        description: "A password matching the given Azure registry username"
        required: true
      helm-repo-username:
        description: "A username with sufficient permissions to push to helm repositories (usually in chartmuseum)"
        required: true
      helm-repo-password:
        description: "A password matching the given helm repo username"
        required: true
      slack-bot-token:
        description: "A slack bot token allowed to post to the Fountain slack"
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: onboardiq/gh-common-workflows
          path: ./common-workflows
          
      - uses: ./common-workflows/.github/workflows/actions/build-assets
        if: ${{ inputs.build-assets }}
        
      - uses: ./common-workflows/.github/workflows/actions/docker-build
        with:
          image-name: ${{ inputs.project-name }}
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          azure-registry-username: ${{ secrets.azure-registry-username }}
          azure-registry-password: ${{ secrets.azure-registry-password }}
          use-precompiled-assets: ${{ inputs.build-assets }}
          regions: ${{ toJSON(fromJSON(inputs.clusters).*.region) }}
  helm:
    needs:
      - docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(inputs.clusters) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: onboardiq/gh-common-workflows
          path: ./common-workflows

      - uses: ./common-workflows/.github/workflows/actions/helm-push
        with:
          image-name: ${{ inputs.project-name }}
          helm-version: ${{ inputs.helm-version }}
          chart-version: ${{ inputs.helm-chart-version }}
          repo-username: ${{ secrets.helm-repo-username }}
          repo-password: ${{ secrets.helm-repo-password}}
          cloud: ${{ matrix.cloud }}
          region: ${{ matrix.region }}
          cluster-suffix: ${{ matrix.cluster-suffix }}

  slack:
    if: ${{ always() }}
    needs:
      - docker
      - helm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: onboardiq/gh-common-workflows
          path: ./common-workflows

      - uses: ./common-workflows/.github/workflows/actions/notify-slack-pipeline-status
        with:
          slack-channel: ${{ inputs.slack-channel }}
          slack-bot-token: ${{ secrets.slack-bot-token }}
      
