name: pre-commit-hook
on:
  pull_request:
    branches:
      - main
jobs:
  hook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - run: /home/linuxbrew/.linuxbrew/bin/brew intall pre-commit
      - run: pre-commit run --all-files
